# Generated by Django 4.0.6 on 2023-06-04 03:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='postLikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
