# Generated by Django 4.0.6 on 2023-06-04 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_alter_user_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
    ]
